Iris Classification using KNearestNeighbor



Importing Required Libraries

In [1]:
import pandas as pd
import numpy as np

Loading the Iris Data : From Scikit-learn dataset, we are calling the load_iris function and placing it into the iris_dataset variable

In [2]:
from sklearn.datasets import load_iris
iris_dataset=load_iris()

Printing the Keys of Iris Dataset

In [3]:
print("Keys of iris_dataset: \n{}".format(iris_dataset.keys()))

Keys of iris_dataset: 
dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


Printing Description of Iris Dataset

In [4]:
print(iris_dataset['DESCR'][:193] + "\n...")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, pre
...


Printing Target Names of Iris Dataset : Lists species of the flowers we should predict

In [5]:
print("Target_names: {}".format(iris_dataset['target_names']))

Target_names: ['setosa' 'versicolor' 'virginica']


Printing Feature Names of Iris Dataset :  : Lists description of the each features of the flower species

In [6]:
print("Feature_names: {}".format(iris_dataset['feature_names']))

Feature_names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


Printing Type of Data of Iris Dataset

In [7]:
print("Type of data: {}".format(type(iris_dataset['data'])))

Type of data: <class 'numpy.ndarray'>


Printing Shape of Data of Iris Dataset

In [8]:
print("Shape of data: {}".format(iris_dataset['data'].shape))

Shape of data: (150, 4)


Printing First Five Rows of the Data from Iris Dataset

In [9]:
print("First five rows of data:\n{}".format(iris_dataset['data'][:5]))

First five rows of data:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


Printing the Type of the target


In [10]:
print("Type of target: {}".format(type(iris_dataset['target'])))

Type of target: <class 'numpy.ndarray'>


Printing the Shape of the target


In [11]:
print("Shape of target: {}".format(iris_dataset['target'].shape))

Shape of target: (150,)


Printing the target key and exploring the values

In [12]:
print("Target:\n{}".format(iris_dataset['target']))

Target:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


Splitting the Dataset into Training and Testing Data

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    iris_dataset['data'], iris_dataset['target'], random_state=0) 

Shape of all the labels of train_test_split function

In [14]:
print("X_train.shape(): {}".format(X_train.shape))
print("X_test.shape(): {}".format(y_train.shape))
print("y_train.shape(): {}".format(X_test.shape))
print("y_test.shape(): {}".format(y_test.shape))

X_train.shape(): (112, 4)
X_test.shape(): (112,)
y_train.shape(): (38, 4)
y_test.shape(): (38,)


This is KNearestNeighbor machine learning model

In [15]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

Training the Model on Training Data

In [16]:
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

Declaring the Model to New Data

In [17]:
X_new = np.array([[5,2.9,1,0.2]])
print("X_new.shape: {}".format(X_new.shape))

X_new.shape: (1, 4)


Printing the prediction of the model

In [18]:
prediction = knn.predict(X_new)
print("Prediction: {}".format(prediction))
print("Predicted Target Name: {}".format(
    iris_dataset['target_names'][prediction]))

Prediction: [0]
Predicted Target Name: ['setosa']


Evaluating the model

In [19]:
y_pred = knn.predict(X_test)
print("Test Set Predictions:\n {}".format(y_pred))

Test Set Predictions:
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


Printing the Test Set Score

In [20]:
print("Test Set Score: {}".format(np.mean(y_pred == y_test)))

Test Set Score: 0.9736842105263158
